### ISSUE TITLE
Precompiled module doesn't work

### ISSUE THREAD

**Issue by CarsterX** [90N45-d3v/DNSspoof-Pineapple-MK7-Module#1]
"Entropy bunny couldn't find that"

**Comment by 90N45-d3v** [comment]
Hmm... maybe reload the module page (http://172.16.42.1:1471/#/Modules/dnsspoof)?
When you install it and run it without a reboot, it will give you "Entropy bunny couldn't find that".
Just reloading the page (or a reboot) should do the job.

If that won't fix it, you may want to tell me exactly what you did to get the folder onto your pineapple?

**Comment by 90N45-d3v** [comment]
Can I close this issue? Do you still have problems according to DNSspoof?
